// Design Presets — curated room layouts inspired by real interior design styles
// Each preset has a name, description, icon, cultural/style inspiration,
// room dimensions, and a complete furniture arrangement

export type RoomType = 'living' | 'bedroom' | 'kitchen' | 'bathroom' | 'office' | 'dining';

export interface PresetFurnitureItem {
  fn: string;       // builder function name
  color: string;    // hex color
  mat: string;      // material type: fabric | leather | wood | metal
  pos: [number, number, number]; // x, y, z
  rot?: number;     // rotation in radians
}

export interface DesignPreset {
  id: string;
  name: string;
  description: string;
  icon: string;       // FontAwesome icon class
  accent: string;     // brand accent color
  roomType: RoomType;
  roomWidth: number;
  roomDepth: number;
  roomHeight: number;
  wallColor: string;
  floorType: string;  // hardwood | marble | concrete | carpet | tile
  floorColor: string;
  lightMood: string;  // daylight | golden | evening | night
  skin?: string;      // optional skin id to apply
  furniture: PresetFurnitureItem[];
}

export const DESIGN_PRESETS: DesignPreset[] = [
  // ──────── LIVING ROOM PRESETS ────────
  {
    id: 'italian_living',
    name: 'Italian Modern',
    description: 'Warm terracotta tones with leather accents — inspired by Milanese sophistication',
    icon: 'fa-landmark',
    accent: '#C17F59',
    roomType: 'living',
    roomWidth: 8, roomDepth: 6, roomHeight: 3,
    wallColor: '#FAF8F4',
    floorType: 'tile',
    floorColor: '#E0C8A0',
    lightMood: 'golden',
    skin: 'luxury_marble',
    furniture: [
      { fn: 'createSofa', color: '#9A6B3C', mat: 'leather', pos: [0, 0, -1.8] },
      { fn: 'createCoffeeTable', color: '#5C4033', mat: 'wood', pos: [0, 0, 0] },
      { fn: 'createArmchair', color: '#C17F59', mat: 'leather', pos: [-2.8, 0, -1], rot: Math.PI / 4 },
      { fn: 'createFloorLamp', color: '#C9A96E', mat: 'metal', pos: [-3.2, 0, -2.2] },
      { fn: 'createRug', color: '#C49898', mat: 'fabric', pos: [0, 0, -0.2] },
      { fn: 'createBookshelf', color: '#5C4033', mat: 'wood', pos: [3.4, 0, 0], rot: -Math.PI / 2 },
      { fn: 'createPlant', color: '#C4A882', mat: 'fabric', pos: [3.2, 0, -2.4] },
    ],
  },
  {
    id: 'french_living',
    name: 'French Provincial',
    description: 'Soft pastels, elegant curves — a Parisian salon with romantic charm',
    icon: 'fa-church',
    accent: '#C49898',
    roomType: 'living',
    roomWidth: 7, roomDepth: 5.5, roomHeight: 3.2,
    wallColor: '#FFFFFF',
    floorType: 'hardwood',
    floorColor: '#E0C8A0',
    lightMood: 'daylight',
    skin: 'nordic_light',
    furniture: [
      { fn: 'createSofa', color: '#C49898', mat: 'fabric', pos: [0, 0, -1.5] },
      { fn: 'createCoffeeTable', color: '#E0C8A0', mat: 'wood', pos: [0, 0, 0.2] },
      { fn: 'createArmchair', color: '#E8DCC8', mat: 'fabric', pos: [2.2, 0, -0.8], rot: -Math.PI / 3 },
      { fn: 'createSideTable', color: '#E0C8A0', mat: 'wood', pos: [-2.5, 0, -1.2] },
      { fn: 'createFloorLamp', color: '#C9A96E', mat: 'metal', pos: [-2.7, 0, -2] },
      { fn: 'createRug', color: '#E8DCC8', mat: 'fabric', pos: [0, 0, -0.2] },
      { fn: 'createPlant', color: '#C4A882', mat: 'fabric', pos: [2.8, 0, -2] },
    ],
  },
  {
    id: 'scandi_living',
    name: 'Scandinavian Hygge',
    description: 'Light woods, cozy textures — Nordic minimalism meets warmth',
    icon: 'fa-snowflake',
    accent: '#7A8B6F',
    roomType: 'living',
    roomWidth: 7, roomDepth: 5, roomHeight: 2.8,
    wallColor: '#FFFFFF',
    floorType: 'hardwood',
    floorColor: '#E0C8A0',
    lightMood: 'daylight',
    skin: 'japandi_zen',
    furniture: [
      { fn: 'createSofa', color: '#E8DCC8', mat: 'fabric', pos: [0, 0, -1.5] },
      { fn: 'createCoffeeTable', color: '#E0C8A0', mat: 'wood', pos: [0, 0, 0.3] },
      { fn: 'createOttoman', color: '#7A8B6F', mat: 'fabric', pos: [1.5, 0, 0.3] },
      { fn: 'createFloorLamp', color: '#C0C0C0', mat: 'metal', pos: [-2.8, 0, -1.5] },
      { fn: 'createRug', color: '#E8DCC8', mat: 'fabric', pos: [0, 0, -0.2] },
      { fn: 'createBookshelf', color: '#E0C8A0', mat: 'wood', pos: [3, 0, -0.5], rot: -Math.PI / 2 },
      { fn: 'createPlant', color: '#7A8B6F', mat: 'fabric', pos: [-2.8, 0, -2] },
    ],
  },
  {
    id: 'japanese_living',
    name: 'Japanese Zen',
    description: 'Minimal, grounded, tranquil — wabi-sabi aesthetic with low furniture',
    icon: 'fa-yin-yang',
    accent: '#8A7A6A',
    roomType: 'living',
    roomWidth: 6, roomDepth: 5, roomHeight: 2.6,
    wallColor: '#F5F0E8',
    floorType: 'hardwood',
    floorColor: '#C4A882',
    lightMood: 'daylight',
    skin: 'japandi_zen',
    furniture: [
      { fn: 'createCoffeeTable', color: '#C4A882', mat: 'wood', pos: [0, 0, -0.5] },
      { fn: 'createOttoman', color: '#8A7A6A', mat: 'fabric', pos: [-1.2, 0, -0.5] },
      { fn: 'createRug', color: '#B8A898', mat: 'fabric', pos: [0, 0, -0.3] },
      { fn: 'createPlant', color: '#7A8B6F', mat: 'fabric', pos: [2.2, 0, -1.8] },
      { fn: 'createFloorLamp', color: '#A0A0A8', mat: 'metal', pos: [-2.3, 0, -1.5] },
      { fn: 'createBookshelf', color: '#C4A882', mat: 'wood', pos: [2.4, 0, 0], rot: -Math.PI / 2 },
    ],
  },
  {
    id: 'industrial_living',
    name: 'Industrial Loft',
    description: 'Raw concrete, dark metals — Brooklyn warehouse vibes',
    icon: 'fa-industry',
    accent: '#B87333',
    roomType: 'living',
    roomWidth: 9, roomDepth: 6, roomHeight: 3.5,
    wallColor: '#D4C8B8',
    floorType: 'concrete',
    floorColor: '#8A8680',
    lightMood: 'evening',
    skin: 'industrial_loft',
    furniture: [
      { fn: 'createSofa', color: '#4A4A4A', mat: 'leather', pos: [0, 0, -1.8] },
      { fn: 'createCoffeeTable', color: '#333333', mat: 'metal', pos: [0, 0, 0] },
      { fn: 'createArmchair', color: '#6B5D50', mat: 'fabric', pos: [-3, 0, -1], rot: Math.PI / 4 },
      { fn: 'createFloorLamp', color: '#333333', mat: 'metal', pos: [-3.5, 0, -2.2] },
      { fn: 'createRug', color: '#6B5D50', mat: 'fabric', pos: [0, 0, -0.2] },
      { fn: 'createTVStand', color: '#3B3B3B', mat: 'wood', pos: [0, 0, -2.5] },
      { fn: 'createBookshelf', color: '#333333', mat: 'metal', pos: [3.8, 0, 0], rot: -Math.PI / 2 },
    ],
  },

  // ──────── BEDROOM PRESETS ────────
  {
    id: 'italian_bedroom',
    name: 'Italian Master',
    description: 'Rich walnut and leather — a Florentine master suite',
    icon: 'fa-landmark',
    accent: '#6B4226',
    roomType: 'bedroom',
    roomWidth: 5.5, roomDepth: 4.5, roomHeight: 3,
    wallColor: '#FAF8F4',
    floorType: 'hardwood',
    floorColor: '#8B4513',
    lightMood: 'golden',
    skin: 'luxury_marble',
    furniture: [
      { fn: 'createBed', color: '#F0EDE8', mat: 'fabric', pos: [0, 0, -1.2] },
      { fn: 'createNightstand', color: '#5C4033', mat: 'wood', pos: [-2, 0, -1.5] },
      { fn: 'createNightstand', color: '#5C4033', mat: 'wood', pos: [2, 0, -1.5] },
      { fn: 'createDresser', color: '#5C4033', mat: 'wood', pos: [2.2, 0, 1], rot: -Math.PI / 2 },
      { fn: 'createTableLamp', color: '#C9A96E', mat: 'metal', pos: [-2, 0, -1.5] },
      { fn: 'createTableLamp', color: '#C9A96E', mat: 'metal', pos: [2, 0, -1.5] },
    ],
  },
  {
    id: 'scandi_bedroom',
    name: 'Nordic Calm',
    description: 'Birch wood and soft linen — restful Scandinavian simplicity',
    icon: 'fa-snowflake',
    accent: '#7A8B6F',
    roomType: 'bedroom',
    roomWidth: 5, roomDepth: 4, roomHeight: 2.8,
    wallColor: '#FFFFFF',
    floorType: 'hardwood',
    floorColor: '#E0C8A0',
    lightMood: 'daylight',
    skin: 'nordic_light',
    furniture: [
      { fn: 'createBed', color: '#E8DCC8', mat: 'fabric', pos: [0, 0, -1] },
      { fn: 'createNightstand', color: '#E0C8A0', mat: 'wood', pos: [-1.8, 0, -1.5] },
      { fn: 'createNightstand', color: '#E0C8A0', mat: 'wood', pos: [1.8, 0, -1.5] },
      { fn: 'createPlant', color: '#7A8B6F', mat: 'fabric', pos: [1.8, 0, 1.2] },
      { fn: 'createTableLamp', color: '#E8DCC8', mat: 'fabric', pos: [-1.8, 0, -1.5] },
    ],
  },
  {
    id: 'japanese_bedroom',
    name: 'Zen Retreat',
    description: 'Low platform bed, minimal decor — Japanese bedroom tranquility',
    icon: 'fa-yin-yang',
    accent: '#8A7A6A',
    roomType: 'bedroom',
    roomWidth: 4.5, roomDepth: 4, roomHeight: 2.6,
    wallColor: '#F5F0E8',
    floorType: 'hardwood',
    floorColor: '#C4A882',
    lightMood: 'daylight',
    skin: 'japandi_zen',
    furniture: [
      { fn: 'createBed', color: '#B8A898', mat: 'fabric', pos: [0, 0, -0.8] },
      { fn: 'createNightstand', color: '#C4A882', mat: 'wood', pos: [-1.6, 0, -1.2] },
      { fn: 'createPlant', color: '#7A8B6F', mat: 'fabric', pos: [1.6, 0, -1.2] },
      { fn: 'createFloorLamp', color: '#A0A0A8', mat: 'metal', pos: [-1.8, 0, 1.2] },
    ],
  },
  {
    id: 'industrial_bedroom',
    name: 'Loft Bedroom',
    description: 'Exposed brick accent, dark metals — urban dwelling',
    icon: 'fa-industry',
    accent: '#B87333',
    roomType: 'bedroom',
    roomWidth: 5, roomDepth: 4, roomHeight: 3.2,
    wallColor: '#E8E2D8',
    floorType: 'concrete',
    floorColor: '#8A8680',
    lightMood: 'evening',
    skin: 'industrial_loft',
    furniture: [
      { fn: 'createBed', color: '#4A4A4A', mat: 'leather', pos: [0, 0, -1] },
      { fn: 'createNightstand', color: '#333333', mat: 'metal', pos: [-1.8, 0, -1.5] },
      { fn: 'createNightstand', color: '#333333', mat: 'metal', pos: [1.8, 0, -1.5] },
      { fn: 'createWardrobe', color: '#3B3B3B', mat: 'wood', pos: [2, 0, 0.5], rot: -Math.PI / 2 },
      { fn: 'createFloorLamp', color: '#333333', mat: 'metal', pos: [-2, 0, 1.2] },
    ],
  },

  // ──────── KITCHEN PRESETS ────────
  {
    id: 'italian_kitchen',
    name: 'Italian Kitchen',
    description: 'Warm marble, brass fixtures — a Tuscan family kitchen',
    icon: 'fa-landmark',
    accent: '#C17F59',
    roomType: 'kitchen',
    roomWidth: 5, roomDepth: 4, roomHeight: 3,
    wallColor: '#FAF8F4',
    floorType: 'tile',
    floorColor: '#E0C8A0',
    lightMood: 'golden',
    skin: 'luxury_marble',
    furniture: [
      { fn: 'createKitchenCounter', color: '#E0C8A0', mat: 'wood', pos: [-0.8, 0, -1.3] },
      { fn: 'createKitchenIsland', color: '#5C4033', mat: 'wood', pos: [0.5, 0, 0.5] },
      { fn: 'createBarStool', color: '#9A6B3C', mat: 'leather', pos: [-0.2, 0, 1.4] },
      { fn: 'createBarStool', color: '#9A6B3C', mat: 'leather', pos: [0.6, 0, 1.4] },
      { fn: 'createBarStool', color: '#9A6B3C', mat: 'leather', pos: [1.2, 0, 1.4] },
      { fn: 'createPlant', color: '#7A8B6F', mat: 'fabric', pos: [2, 0, -1.3] },
    ],
  },
  {
    id: 'scandi_kitchen',
    name: 'Nordic Kitchen',
    description: 'Bright, white cabinetry with birch accents — clean and functional',
    icon: 'fa-snowflake',
    accent: '#7A8B6F',
    roomType: 'kitchen',
    roomWidth: 4, roomDepth: 3.5, roomHeight: 2.8,
    wallColor: '#FFFFFF',
    floorType: 'hardwood',
    floorColor: '#E0C8A0',
    lightMood: 'daylight',
    skin: 'nordic_light',
    furniture: [
      { fn: 'createKitchenCounter', color: '#F0EDE8', mat: 'wood', pos: [-0.5, 0, -1] },
      { fn: 'createKitchenIsland', color: '#E0C8A0', mat: 'wood', pos: [0, 0, 0.5] },
      { fn: 'createBarStool', color: '#E8DCC8', mat: 'fabric', pos: [-0.4, 0, 1.2] },
      { fn: 'createBarStool', color: '#E8DCC8', mat: 'fabric', pos: [0.4, 0, 1.2] },
      { fn: 'createPlant', color: '#7A8B6F', mat: 'fabric', pos: [1.5, 0, -1] },
    ],
  },
  {
    id: 'industrial_kitchen',
    name: 'Industrial Kitchen',
    description: 'Dark countertops, open shelving — professional-grade home kitchen',
    icon: 'fa-industry',
    accent: '#B87333',
    roomType: 'kitchen',
    roomWidth: 5, roomDepth: 4, roomHeight: 3,
    wallColor: '#B8B4B0',
    floorType: 'concrete',
    floorColor: '#8A8680',
    lightMood: 'evening',
    skin: 'industrial_loft',
    furniture: [
      { fn: 'createKitchenCounter', color: '#3B3B3B', mat: 'wood', pos: [-0.8, 0, -1.3] },
      { fn: 'createKitchenIsland', color: '#3B3B3B', mat: 'wood', pos: [0.5, 0, 0.5] },
      { fn: 'createBarStool', color: '#333333', mat: 'metal', pos: [-0.2, 0, 1.4] },
      { fn: 'createBarStool', color: '#333333', mat: 'metal', pos: [0.6, 0, 1.4] },
      { fn: 'createBarStool', color: '#333333', mat: 'metal', pos: [1.2, 0, 1.4] },
    ],
  },

  // ──────── OFFICE PRESETS ────────
  {
    id: 'scandi_office',
    name: 'Nordic Office',
    description: 'Clean lines, natural light — productive Scandinavian workspace',
    icon: 'fa-snowflake',
    accent: '#7A8B6F',
    roomType: 'office',
    roomWidth: 4, roomDepth: 3.5, roomHeight: 3,
    wallColor: '#FFFFFF',
    floorType: 'hardwood',
    floorColor: '#E0C8A0',
    lightMood: 'daylight',
    skin: 'nordic_light',
    furniture: [
      { fn: 'createDesk', color: '#E0C8A0', mat: 'wood', pos: [0, 0, -1.2] },
      { fn: 'createOfficeChair', color: '#8A8478', mat: 'fabric', pos: [0, 0, -0.5] },
      { fn: 'createFilingCabinet', color: '#C0C0C0', mat: 'metal', pos: [1.5, 0, -1.2] },
      { fn: 'createMonitorStand', color: '#C0C0C0', mat: 'metal', pos: [0, 0, -1.4] },
      { fn: 'createPlant', color: '#7A8B6F', mat: 'fabric', pos: [-1.5, 0, -1.2] },
      { fn: 'createBookshelf', color: '#E0C8A0', mat: 'wood', pos: [1.6, 0, 0.8], rot: -Math.PI / 2 },
    ],
  },
  {
    id: 'industrial_office',
    name: 'Loft Office',
    description: 'Raw brick, open shelving — creative studio energy',
    icon: 'fa-industry',
    accent: '#B87333',
    roomType: 'office',
    roomWidth: 5, roomDepth: 4, roomHeight: 3.2,
    wallColor: '#D4C8B8',
    floorType: 'concrete',
    floorColor: '#8A8680',
    lightMood: 'evening',
    skin: 'industrial_loft',
    furniture: [
      { fn: 'createDesk', color: '#3B3B3B', mat: 'wood', pos: [0, 0, -1.2] },
      { fn: 'createOfficeChair', color: '#2D2D2D', mat: 'leather', pos: [0, 0, -0.5] },
      { fn: 'createFilingCabinet', color: '#333333', mat: 'metal', pos: [1.8, 0, -1.2] },
      { fn: 'createMonitorStand', color: '#333333', mat: 'metal', pos: [0, 0, -1.4] },
      { fn: 'createBookshelf', color: '#333333', mat: 'metal', pos: [2, 0, 0.8], rot: -Math.PI / 2 },
      { fn: 'createPlant', color: '#7A8B6F', mat: 'fabric', pos: [-2, 0, -1.2] },
    ],
  },

  // ──────── DINING PRESETS ────────
  {
    id: 'italian_dining',
    name: 'Italian Dining',
    description: 'Grand table, warm candlelight — la dolce vita family feasts',
    icon: 'fa-landmark',
    accent: '#C17F59',
    roomType: 'dining',
    roomWidth: 5.5, roomDepth: 4.5, roomHeight: 3,
    wallColor: '#FAF8F4',
    floorType: 'hardwood',
    floorColor: '#8B4513',
    lightMood: 'golden',
    skin: 'luxury_marble',
    furniture: [
      { fn: 'createDiningTable', color: '#5C4033', mat: 'wood', pos: [0, 0, 0] },
      { fn: 'createDiningChair', color: '#9A6B3C', mat: 'leather', pos: [-0.6, 0, 0.8] },
      { fn: 'createDiningChair', color: '#9A6B3C', mat: 'leather', pos: [0.6, 0, 0.8] },
      { fn: 'createDiningChair', color: '#9A6B3C', mat: 'leather', pos: [-0.6, 0, -0.8] },
      { fn: 'createDiningChair', color: '#9A6B3C', mat: 'leather', pos: [0.6, 0, -0.8] },
      { fn: 'createPendant', color: '#C9A96E', mat: 'metal', pos: [0, 0, 0] },
      { fn: 'createPlant', color: '#7A8B6F', mat: 'fabric', pos: [2.2, 0, -1.8] },
    ],
  },
  {
    id: 'scandi_dining',
    name: 'Nordic Dining',
    description: 'Light wood, simple chairs — Scandinavian communal meals',
    icon: 'fa-snowflake',
    accent: '#7A8B6F',
    roomType: 'dining',
    roomWidth: 5, roomDepth: 4, roomHeight: 2.8,
    wallColor: '#FFFFFF',
    floorType: 'hardwood',
    floorColor: '#E0C8A0',
    lightMood: 'daylight',
    skin: 'nordic_light',
    furniture: [
      { fn: 'createDiningTable', color: '#E0C8A0', mat: 'wood', pos: [0, 0, 0] },
      { fn: 'createDiningChair', color: '#E8DCC8', mat: 'fabric', pos: [-0.6, 0, 0.7] },
      { fn: 'createDiningChair', color: '#E8DCC8', mat: 'fabric', pos: [0.6, 0, 0.7] },
      { fn: 'createDiningChair', color: '#E8DCC8', mat: 'fabric', pos: [-0.6, 0, -0.7] },
      { fn: 'createDiningChair', color: '#E8DCC8', mat: 'fabric', pos: [0.6, 0, -0.7] },
      { fn: 'createPendant', color: '#C0C0C0', mat: 'metal', pos: [0, 0, 0] },
      { fn: 'createPlant', color: '#7A8B6F', mat: 'fabric', pos: [2, 0, -1.5] },
    ],
  },
  {
    id: 'french_dining',
    name: 'French Bistro',
    description: 'Bistro chairs, bistro lighting — a cozy Parisian dinner',
    icon: 'fa-church',
    accent: '#C49898',
    roomType: 'dining',
    roomWidth: 4.5, roomDepth: 3.5, roomHeight: 3,
    wallColor: '#FAF8F4',
    floorType: 'tile',
    floorColor: '#E0C8A0',
    lightMood: 'golden',
    skin: 'nordic_light',
    furniture: [
      { fn: 'createDiningTable', color: '#5C4033', mat: 'wood', pos: [0, 0, 0] },
      { fn: 'createDiningChair', color: '#C49898', mat: 'fabric', pos: [-0.5, 0, 0.6] },
      { fn: 'createDiningChair', color: '#C49898', mat: 'fabric', pos: [0.5, 0, 0.6] },
      { fn: 'createDiningChair', color: '#C49898', mat: 'fabric', pos: [-0.5, 0, -0.6] },
      { fn: 'createDiningChair', color: '#C49898', mat: 'fabric', pos: [0.5, 0, -0.6] },
      { fn: 'createPendant', color: '#C9A96E', mat: 'metal', pos: [0, 0, 0] },
    ],
  },

  // ──────── BATHROOM PRESETS ────────
  {
    id: 'luxury_bathroom',
    name: 'Spa Luxury',
    description: 'Marble surfaces, soft lighting — a five-star bathroom retreat',
    icon: 'fa-gem',
    accent: '#C9A96E',
    roomType: 'bathroom',
    roomWidth: 3.5, roomDepth: 3, roomHeight: 2.8,
    wallColor: '#F0EDE8',
    floorType: 'marble',
    floorColor: '#E0D8D0',
    lightMood: 'daylight',
    skin: 'luxury_marble',
    furniture: [
      { fn: 'createBathtub', color: '#F0EDE8', mat: 'fabric', pos: [-0.7, 0, -0.8] },
      { fn: 'createToilet', color: '#F5F5F0', mat: 'fabric', pos: [1.2, 0, -1] },
      { fn: 'createPedestalSink', color: '#F5F5F0', mat: 'fabric', pos: [1.2, 0, 0.8] },
      { fn: 'createPlant', color: '#7A8B6F', mat: 'fabric', pos: [-1.2, 0, 0.8] },
    ],
  },
  {
    id: 'industrial_bathroom',
    name: 'Industrial Bath',
    description: 'Concrete and glass — moody, modern bathroom',
    icon: 'fa-industry',
    accent: '#B87333',
    roomType: 'bathroom',
    roomWidth: 3, roomDepth: 2.5, roomHeight: 2.8,
    wallColor: '#B8B4B0',
    floorType: 'concrete',
    floorColor: '#8A8680',
    lightMood: 'evening',
    skin: 'industrial_loft',
    furniture: [
      { fn: 'createShower', color: '#C0C0C0', mat: 'metal', pos: [-0.7, 0, -0.5] },
      { fn: 'createToilet', color: '#F5F5F0', mat: 'fabric', pos: [1, 0, -0.8] },
      { fn: 'createPedestalSink', color: '#F5F5F0', mat: 'fabric', pos: [1, 0, 0.7] },
    ],
  },
];

export function getPresetsForRoom(roomType: RoomType): DesignPreset[] {
  return DESIGN_PRESETS.filter(p => p.roomType === roomType);
}

export function getPresetById(id: string): DesignPreset | undefined {
  return DESIGN_PRESETS.find(p => p.id === id);
}
